// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGa-D4DjSo7hEF0BnhU9ODt6ixes4DYuo',
    appId: '1:464486337181:web:7b317e208cd18a0d25e274',
    messagingSenderId: '464486337181',
    projectId: 'flutterfiresample2',
    authDomain: 'flutterfiresample2.firebaseapp.com',
    storageBucket: 'flutterfiresample2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdcIpkNM6WMwRuwrm4z14fY2-rZiQRiS0',
    appId: '1:464486337181:android:aaaae96fa0cf063f25e274',
    messagingSenderId: '464486337181',
    projectId: 'flutterfiresample2',
    storageBucket: 'flutterfiresample2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC339wUN6y-LISItHNRDc2BMi65edc4mKc',
    appId: '1:464486337181:ios:fc1724119a6b9e4125e274',
    messagingSenderId: '464486337181',
    projectId: 'flutterfiresample2',
    storageBucket: 'flutterfiresample2.appspot.com',
    iosClientId: '464486337181-j0ug9flr1cm5il807ltsdbneebsq8f1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC339wUN6y-LISItHNRDc2BMi65edc4mKc',
    appId: '1:464486337181:ios:fc1724119a6b9e4125e274',
    messagingSenderId: '464486337181',
    projectId: 'flutterfiresample2',
    storageBucket: 'flutterfiresample2.appspot.com',
    iosClientId: '464486337181-j0ug9flr1cm5il807ltsdbneebsq8f1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireApp2',
  );
}
